---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)

options(stringsAsFactors = F)
```


Let's explore how correlated the TSS expression data is to the fragment expression.

```{bash}
# create strand separated files
# standard bed requires integers for score, not float, so cut this column out
awk '{if ($6 == "+") print $0}' ../processed_data/tss_positives.bed | cut -f 1-4 > ../processed_data/tss_positives_plus.bed
awk '{if ($6 == "-") print $0}' ../processed_data/tss_positives.bed | cut -f 1-4 > ../processed_data/tss_positives_minus.bed

awk '{if ($6 == "+") print $0}' ../processed_data/tss_negatives.bed | cut -f 1-4 > ../processed_data/tss_negatives_plus.bed
awk '{if ($6 == "-") print $0}' ../processed_data/tss_negatives.bed | cut -f 1-4 > ../processed_data/tss_negatives_minus.bed
```

```{bash}
bigWigAverageOverBed ../processed_data/expn_wig/U00096.2_plus_expression.bw ../processed_data/tss_positives_plus.bed ../processed_data/tss_positives_plus_exp_avg.txt
bigWigAverageOverBed ../processed_data/expn_wig/U00096.2_plus_expression.bw ../processed_data/tss_negatives_plus.bed ../processed_data/tss_negatives_plus_exp_avg.txt

bigWigAverageOverBed ../processed_data/expn_wig/U00096.2_minus_expression.bw ../processed_data/tss_positives_minus.bed ../processed_data/tss_positives_minus_exp_avg.txt
bigWigAverageOverBed ../processed_data/expn_wig/U00096.2_minus_expression.bw ../processed_data/tss_negatives_minus.bed ../processed_data/tss_negatives_minus_exp_avg.txt
```

```{r}
names <- c('name', 'size', 'covered', 'sum', 'mean0', 'mean')
positive_avg <- bind_rows(read.table('../processed_data/tss_positives_plus_exp_avg.txt'),
                          read.table('../processed_data/tss_positives_minus_exp_avg.txt'))
names(positive_avg) <- names

negative_avg <- bind_rows(read.table('../processed_data/tss_negatives_plus_exp_avg.txt'),
                          read.table('../processed_data/tss_negatives_minus_exp_avg.txt'))
names(negative_avg) <- names

positive_bed <- read.table('../processed_data/tss_positives.bed',
                           col.names = c('chrom', 'start', 'end', 'name', 'exp', 'strand'))
negative_bed <- read.table('../processed_data/tss_negatives.bed',
                           col.names = c('chrom', 'start', 'end', 'name', 'exp', 'strand'),
                           fill = T)

positive_avg <- positive_avg %>% 
    left_join(select(positive_bed, name, exp), by = 'name') %>% 
    mutate(type = 'active')

negative_avg <- negative_avg %>% 
    left_join(select(negative_bed, name, exp), by = 'name') %>% 
    mutate(type = 'inactive')

avg_all <- bind_rows(positive_avg, negative_avg)
```

```{r}
fit <- summary(lm(mean ~ exp, avg_all))$r.squared
ggplot(avg_all, aes(exp, mean)) + geom_point(alpha = 0.25) +
    scale_x_log10() + scale_y_log10() + annotation_logticks(sides = 'bl') +
    annotate('text', x = 75, y = 0.10, parse = T, label = paste('R^2==', signif(fit, 3))) +
    labs(x = 'TSS library expression',
         y = 'mean genome frag.')
```

```{r}
fit <- summary(lm(mean ~ exp, filter(avg_all, type == 'inactive')))$r.squared

avg_all %>% 
    filter(type == 'inactive') %>% 
    ggplot(aes(exp, mean)) + geom_point(alpha = 0.25) +
        scale_x_log10() + scale_y_log10() + annotation_logticks(sides = 'bl') +
        annotate('text', x = 1.2, y = 0.10, parse = T, label = paste('R^2==', signif(fit, 3))) +
        labs(x = 'TSS library expression',
             y = 'mean genome frag.',
             title = 'Inactive TSSs')
```


```{r}
fit <- summary(lm(mean ~ exp, filter(avg_all, type == 'active')))$r.squared

avg_all %>% 
    filter(type == 'active') %>% 
    ggplot(aes(exp, mean)) + geom_point(alpha = 0.25) +
        scale_x_log10() + scale_y_log10() + annotation_logticks(sides = 'bl') +
        annotate('text', x = 100, y = 0.75, parse = T, label = paste('R^2==', signif(fit, 3))) +
        labs(x = 'TSS library expression',
             y = 'mean genome frag.',
             title = 'Active TSSs')
```

